
name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的提交历史
      
      - name: Set Git user information
        run: |
          git config --global user.email "759837901@qq.com"
          git config --global user.name "Qiming Zhu"

      - name: Fetch upstream repo
        run: |
          git remote add upstream https://github.com/domaineval/DomainEval.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --no-edit

      - name: Push changes to forked repo
        run: |
          git push origin main
